#!/bin/sh -e

if [ -e /nix ]; then
    >&2 echo "Cannot use runexp inside nix environment!"
    exit 1
fi

#>&2 echo Running runexp for MN4
#>&2 echo PATH=$PATH

user=$(id -un)
group=$(id -gn)

export GARLIC_OUT="/gpfs/projects/bsc15/garlic/out/$user"
mkdir -p "$GARLIC_OUT"
cd "$GARLIC_OUT"

exec @nixPrefix@@program@
