#!/bin/sh -ex
# @upload-to-mn@

# This program runs the current experiment in the ./result symlink in
# MareNostrum. Requires that you define a "mn" host in the ssh config file
# (usually in ~/.ssh/config).

nixPrefix=@nixPrefix@
nixtools=$nixPrefix@nixtools@/bin
runexp=$nixtools/@targetCluster@/runexp

>&2 echo "Launching \"$runexp @program@\" in MN"

ssh mn $runexp @program@
