.\".fam CMU
.\".TL
.\"Garlic: git branch name
.\".AU
.\"Rodrigo Arias Mallo
.\".AI
.\"Barcelona Supercomputing Center
.\"#####################################################################
.nr GROWPS 3
.nr PSINCR 1.5p
.\".nr PD 0.5m
.nr PI 2m
\".2C
.\"#####################################################################
\".NH 1
\"Instructions
\".LP
\"To name a branch of a program, please follow the flowchart below.
.ps -2
.PS 5/25.4
copy "gitbranch.pic"
.PE
