#!/bin/sh -e

#>&2 echo Running isolate stage2
#>&2 echo PATH=$PATH

if [ ! -e /nix ]; then
  >&2 echo "/nix not found, aborting" 
  exit 1
fi

if [ -e /usr ]; then
  >&2 echo "Environment not isolated, aborting"
  exit 1
fi

exec @program@
