#!/bin/bash -e

#>&2 echo Running isolate stage1
#>&2 echo PATH=$PATH

if [ -e /nix ]; then
  >&2 echo "/nix found, aborting"
  exit 1
fi

nixhome="@nixPrefix@/nix"
shell="@busybox@/bin/sh"
nixjoin="@nixPrefix@@nixtools@/bin/nix-join"


env=(
  PATH="@nixPrefix@@busybox@/bin:@busybox@/bin:@extraPath@"
  $(env | grep ^SLURM || true)
  $(env | grep ^PMI || true)
  $(env | grep ^GARLIC || true)
  $(env | grep ^USER || true)
  $(env | grep ^TMPDIR || true)
  $(env | grep '^TERM=' || true)
  HOME="/homeless-shelter"
)

mounts=(
	#-m @nixPrefix@
	#FIXME: Use only the strictly neccesary from /etc
	-m /original-etc:/etc
	# The /etc/hosts file is a symlink to this etc/
	-m /.statelite/tmpfs/etc
	-m /sys
	-m /dev
	-m /proc
	# nscd cache: doesn't exist (?)
	#-m /var/run/nscd
	# Needed for munge auth
	-m /var/run/munge
	# FIXME: We should only need nix and the output path
	-m /gpfs/projects/bsc15
	-m /gpfs/scratch/bsc15
	-m /bin:@nixPrefix@@busybox@/bin
	-m "$TMPDIR"
	@extraMountOptions@
)

symlinks=(
  -s /etc/hosts:/original-etc/hosts
  -s /etc/passwd:/original-etc/passwd
  -s /etc/resolv.conf:/original-etc/resolv.conf
  -s /etc/host.conf:/original-etc/host.conf
  -s /etc/slurm/slurm.conf:/original-etc/slurm/slurm.conf
  -s /etc/services:/original-etc/services
)

exec $nixjoin -i "${mounts[@]}" "${symlinks[@]}" $nixhome -- \
	env -i "${env[@]}" @out@/bin/stage2 "$@"
